[CmdletBinding()]
param(
    [string]$ProjectRoot,
    [string]$KeyArtPath = 'art_refs/characters/coco/concept/Coco_KeyArt_REVIEW_v002.png',
    [string]$TurnaroundPath = 'art_refs/characters/coco/turnaround/Coco_Turnaround_REVIEW_v001.png',
    [string]$ExpressionPath = 'art_refs/characters/coco/expressions/Coco_ExpressionSheet_REVIEW_v001.png',
    [string]$EquipmentPath = 'art_refs/characters/coco/equipment/Coco_EquipmentSheet_REVIEW_v001.png',
    [string]$PalettePath = 'art_refs/characters/coco/concept/Coco_MaterialPalette_REVIEW_v001.png',
    [string]$TranslationPath = 'art_refs/characters/coco/3d_reference/Coco_2DTo3DTranslation_REVIEW_v001.png',
    [string]$Face128Path = 'art_refs/characters/coco/concept/Coco_Face128_REVIEW_v001.png',
    [string]$SilhouettePath = 'art_refs/characters/coco/concept/Coco_SilhouetteTest_REVIEW_v001.png',
    [string]$OutputPath = 'art_refs/characters/coco/Coco_CharacterSheet_REVIEW_v001.png',
    [switch]$Force
)

Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
Add-Type -AssemblyName System.Drawing

if([string]::IsNullOrWhiteSpace($ProjectRoot)){$ProjectRoot=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'))}else{$ProjectRoot=[IO.Path]::GetFullPath($ProjectRoot)}
function Resolve-In([string]$Path){$p=if([IO.Path]::IsPathRooted($Path)){$Path}else{Join-Path $ProjectRoot $Path};return (Resolve-Path -LiteralPath $p -ErrorAction Stop).Path}
function Resolve-Out([string]$Path){if([IO.Path]::IsPathRooted($Path)){return [IO.Path]::GetFullPath($Path)};return [IO.Path]::GetFullPath((Join-Path $ProjectRoot $Path))}
function C([string]$Hex){return [Drawing.ColorTranslator]::FromHtml($Hex)}
function F([float]$Size,[Drawing.FontStyle]$Style=[Drawing.FontStyle]::Regular){try{return [Drawing.Font]::new('Segoe UI',$Size,$Style,[Drawing.GraphicsUnit]::Pixel)}catch{return [Drawing.Font]::new([Drawing.FontFamily]::GenericSansSerif,$Size,$Style,[Drawing.GraphicsUnit]::Pixel)}}
function Init-G([Drawing.Graphics]$G){$G.SmoothingMode=[Drawing.Drawing2D.SmoothingMode]::AntiAlias;$G.InterpolationMode=[Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic;$G.PixelOffsetMode=[Drawing.Drawing2D.PixelOffsetMode]::HighQuality;$G.CompositingQuality=[Drawing.Drawing2D.CompositingQuality]::HighQuality;$G.TextRenderingHint=[Drawing.Text.TextRenderingHint]::AntiAliasGridFit}
function Draw-Text([Drawing.Graphics]$G,[string]$Text,[Drawing.Font]$Font,[Drawing.Brush]$Brush,[Drawing.RectangleF]$Rect,[Drawing.StringAlignment]$Align=[Drawing.StringAlignment]::Near,[Drawing.StringAlignment]$Line=[Drawing.StringAlignment]::Near){$sf=[Drawing.StringFormat]::new();try{$sf.Alignment=$Align;$sf.LineAlignment=$Line;$sf.Trimming=[Drawing.StringTrimming]::EllipsisCharacter;$G.DrawString($Text,$Font,$Brush,$Rect,$sf)}finally{$sf.Dispose()}}
function Draw-ImageFit([Drawing.Graphics]$G,[Drawing.Image]$Image,[Drawing.RectangleF]$Bounds){$scale=[Math]::Min($Bounds.Width/$Image.Width,$Bounds.Height/$Image.Height);$w=$Image.Width*$scale;$h=$Image.Height*$scale;$x=$Bounds.X+($Bounds.Width-$w)/2;$y=$Bounds.Y+($Bounds.Height-$h)/2;$dest=[Drawing.Rectangle]::new([int][Math]::Round($x),[int][Math]::Round($y),[int][Math]::Round($w),[int][Math]::Round($h));$G.DrawImage($Image,$dest)}
function Draw-Frame([Drawing.Graphics]$G,[Drawing.Image]$Image,[Drawing.Rectangle]$Bounds,[string]$Title,[string]$Subtitle,[Drawing.Color]$Accent,[Drawing.Font]$TitleFont,[Drawing.Font]$SubFont){$panel=[Drawing.SolidBrush]::new((C '#0E1929'));$border=[Drawing.Pen]::new((C '#2A3B51'),3);$accentBrush=[Drawing.SolidBrush]::new($Accent);$white=[Drawing.SolidBrush]::new((C '#F8FAFC'));$muted=[Drawing.SolidBrush]::new((C '#93A4BA'));try{$G.FillRectangle($panel,$Bounds);$G.DrawRectangle($border,$Bounds);$G.FillRectangle($accentBrush,$Bounds.X,$Bounds.Y,8,$Bounds.Height);Draw-Text $G $Title $TitleFont $white ([Drawing.RectangleF]::new($Bounds.X+28,$Bounds.Y+18,$Bounds.Width-55,38));Draw-Text $G $Subtitle $SubFont $muted ([Drawing.RectangleF]::new($Bounds.X+30,$Bounds.Y+59,$Bounds.Width-60,28));Draw-ImageFit $G $Image ([Drawing.RectangleF]::new($Bounds.X+24,$Bounds.Y+105,$Bounds.Width-48,$Bounds.Height-132))}finally{$muted.Dispose();$white.Dispose();$accentBrush.Dispose();$border.Dispose();$panel.Dispose()}}
function Status-Color([string]$Kind){switch($Kind){'pass'{return C '#61E6A5'}'auto'{return C '#35E9B7'}'pending'{return C '#F7B955'}'partial'{return C '#A78BFA'}'conditional'{return C '#F09A78'}default{return C '#FF8EA3'}}}
function Draw-Table([Drawing.Graphics]$G,[Drawing.Rectangle]$Bounds,[string]$Title,[object[]]$Rows,[int]$RowHeight,[Drawing.Color]$Accent,[Drawing.Font]$TitleFont,[Drawing.Font]$HeaderFont,[Drawing.Font]$IdFont,[Drawing.Font]$BodyFont,[Drawing.Font]$StateFont){$panel=[Drawing.SolidBrush]::new((C '#0E1929'));$header=[Drawing.SolidBrush]::new((C '#132238'));$alt=[Drawing.SolidBrush]::new((C '#101D2F'));$white=[Drawing.SolidBrush]::new((C '#F8FAFC'));$muted=[Drawing.SolidBrush]::new((C '#93A4BA'));$accentBrush=[Drawing.SolidBrush]::new($Accent);$border=[Drawing.Pen]::new((C '#2A3B51'),2);$grid=[Drawing.Pen]::new((C '#23354A'),1);try{$G.FillRectangle($panel,$Bounds);$G.DrawRectangle($border,$Bounds);$G.FillRectangle($accentBrush,$Bounds.X,$Bounds.Y,8,$Bounds.Height);Draw-Text $G $Title $TitleFont $white ([Drawing.RectangleF]::new($Bounds.X+28,$Bounds.Y+18,$Bounds.Width-50,42));$hy=$Bounds.Y+72;$G.FillRectangle($header,$Bounds.X+8,$hy,$Bounds.Width-10,46);Draw-Text $G 'ID' $HeaderFont $muted ([Drawing.RectangleF]::new($Bounds.X+28,$hy,180,46)) Near Center;Draw-Text $G 'CHECK' $HeaderFont $muted ([Drawing.RectangleF]::new($Bounds.X+220,$hy,930,46)) Near Center;Draw-Text $G 'STATE' $HeaderFont $muted ([Drawing.RectangleF]::new($Bounds.X+1190,$hy,$Bounds.Width-1210,46)) Near Center;$y=$hy+46;for($i=0;$i-lt$Rows.Count;$i++){$row=$Rows[$i];if(($i%2)-eq1){$G.FillRectangle($alt,$Bounds.X+8,$y,$Bounds.Width-10,$RowHeight)};$G.DrawLine($grid,$Bounds.X+8,$y+$RowHeight,$Bounds.Right-2,$y+$RowHeight);$sb=[Drawing.SolidBrush]::new((Status-Color $row.Kind));try{Draw-Text $G $row.Id $IdFont $white ([Drawing.RectangleF]::new($Bounds.X+28,$y,180,$RowHeight)) Near Center;Draw-Text $G $row.Check $BodyFont $white ([Drawing.RectangleF]::new($Bounds.X+220,$y,930,$RowHeight)) Near Center;Draw-Text $G $row.State $StateFont $sb ([Drawing.RectangleF]::new($Bounds.X+1190,$y,$Bounds.Width-1210,$RowHeight)) Near Center}finally{$sb.Dispose()};$y+=$RowHeight}}finally{$grid.Dispose();$border.Dispose();$accentBrush.Dispose();$muted.Dispose();$white.Dispose();$alt.Dispose();$header.Dispose();$panel.Dispose()}}
function Draw-Badge([Drawing.Graphics]$G,[Drawing.Rectangle]$Bounds,[string]$Label,[string]$Value,[Drawing.Color]$Accent,[Drawing.Font]$LabelFont,[Drawing.Font]$ValueFont){$panel=[Drawing.SolidBrush]::new((C '#132238'));$muted=[Drawing.SolidBrush]::new((C '#93A4BA'));$valueBrush=[Drawing.SolidBrush]::new($Accent);$border=[Drawing.Pen]::new([Drawing.Color]::FromArgb(190,$Accent),2);try{$G.FillRectangle($panel,$Bounds);$G.DrawRectangle($border,$Bounds);Draw-Text $G $Label $LabelFont $muted ([Drawing.RectangleF]::new($Bounds.X+20,$Bounds.Y+10,$Bounds.Width-40,30));Draw-Text $G $Value $ValueFont $valueBrush ([Drawing.RectangleF]::new($Bounds.X+20,$Bounds.Y+42,$Bounds.Width-40,38))}finally{$border.Dispose();$valueBrush.Dispose();$muted.Dispose();$panel.Dispose()}}

$paths=[ordered]@{KeyArt=Resolve-In $KeyArtPath;Turnaround=Resolve-In $TurnaroundPath;Expressions=Resolve-In $ExpressionPath;Equipment=Resolve-In $EquipmentPath;Palette=Resolve-In $PalettePath;Translation=Resolve-In $TranslationPath;Face128=Resolve-In $Face128Path;Silhouette=Resolve-In $SilhouettePath}
$images=[ordered]@{};foreach($e in $paths.GetEnumerator()){$images[$e.Key]=[Drawing.Bitmap]::FromFile($e.Value)}
$expected=[ordered]@{KeyArt=@(864,1821);Turnaround=@(1536,1024);Expressions=@(1705,922);Equipment=@(1024,1536);Palette=@(1600,1160);Translation=@(2048,1440);Face128=@(128,128);Silhouette=@(1600,960)}
foreach($e in $expected.GetEnumerator()){if($images[$e.Key].Width-ne$e.Value[0]-or$images[$e.Key].Height-ne$e.Value[1]){throw "$($e.Key) dimensions changed: expected $($e.Value[0])x$($e.Value[1]), got $($images[$e.Key].Width)x$($images[$e.Key].Height)."}}
$out=Resolve-Out $OutputPath;if([IO.File]::Exists($out)-and-not$Force){throw "Output exists: $out. Use -Force."};$dir=Split-Path -Parent $out;if(-not[IO.Directory]::Exists($dir)){[IO.Directory]::CreateDirectory($dir)|Out-Null}
$canvas=[Drawing.Bitmap]::new(4096,4608,[Drawing.Imaging.PixelFormat]::Format24bppRgb);$g=[Drawing.Graphics]::FromImage($canvas)
$fonts=@{Header=F 54 ([Drawing.FontStyle]::Bold);HeaderSub=F 24;SummaryTitle=F 25 ([Drawing.FontStyle]::Bold);Summary=F 22;FrameTitle=F 27 ([Drawing.FontStyle]::Bold);FrameSub=F 18;TableTitle=F 28 ([Drawing.FontStyle]::Bold);TableHeader=F 17 ([Drawing.FontStyle]::Bold);TableId=F 18 ([Drawing.FontStyle]::Bold);TableBody=F 18;TableState=F 17 ([Drawing.FontStyle]::Bold);BadgeLabel=F 17 ([Drawing.FontStyle]::Bold);BadgeValue=F 22 ([Drawing.FontStyle]::Bold);EvidenceTitle=F 24 ([Drawing.FontStyle]::Bold);Footer=F 20 ([Drawing.FontStyle]::Bold)}
try{
 Init-G $g;$bg=[Drawing.SolidBrush]::new((C '#07111F'));$white=[Drawing.SolidBrush]::new((C '#F8FAFC'));$muted=[Drawing.SolidBrush]::new((C '#93A4BA'));$jade=[Drawing.SolidBrush]::new((C '#35E9B7'));$amber=[Drawing.SolidBrush]::new((C '#F7B955'));$panel=[Drawing.SolidBrush]::new((C '#0E1929'));$border=[Drawing.Pen]::new((C '#2A3B51'),3);$jadePen=[Drawing.Pen]::new((C '#35E9B7'),3)
 try{
  $g.FillRectangle($bg,0,0,$canvas.Width,$canvas.Height);Draw-Text $g 'COCO / INTEGRATED CHARACTER PRODUCTION SHEET' $fonts.Header $white ([Drawing.RectangleF]::new(48,28,2800,70));Draw-Text $g 'REVIEW v001 | selected 2D identity, production views, equipment, materials, and 2D -> 3D handoff' $fonts.HeaderSub $muted ([Drawing.RectangleF]::new(51,98,3100,38));Draw-Text $g 'REVIEW ONLY / HUMAN APPROVAL NOT GRANTED' $fonts.SummaryTitle $amber ([Drawing.RectangleF]::new(3200,52,840,42)) Far Near;$g.DrawLine($jadePen,48,145,4048,145)
  $summary=[Drawing.Rectangle]::new(48,175,4000,310);$g.FillRectangle($panel,$summary);$g.DrawRectangle($border,$summary);Draw-Text $g 'IDENTITY LOCK' $fonts.SummaryTitle $jade ([Drawing.RectangleF]::new(82,204,500,38));Draw-Text $g 'HOOK  | Warm-smiling rescue captain who takes command when danger peaks' $fonts.Summary $white ([Drawing.RectangleF]::new(82,247,3600,34));Draw-Text $g 'ROLE  | Adult woman / heal + shield support / feminine, healthy-curve rescue silhouette' $fonts.Summary $white ([Drawing.RectangleF]::new(82,287,3600,34));Draw-Text $g 'LOCK  | coral-copper side braid -> low wavy pony / short angular coral half-cape / ivory-charcoal-jade suit' $fonts.Summary $white ([Drawing.RectangleF]::new(82,327,3800,34));Draw-Text $g 'SCOPE | 2D target 7.00-7.20H: measured 7.10H PASS / 3D target 5.50-5.60H: concept 5.55H PRECHECK PASS' $fonts.Summary $jade ([Drawing.RectangleF]::new(82,377,3800,34));Draw-Text $g 'Primary: hair + half-cape silhouette   Secondary: pulse-injector baton + pack/bioscanner/projector' $fonts.Summary $muted ([Drawing.RectangleF]::new(82,422,3800,34))
  $fw=1312;$fh=900;$xs=@(48,1392,2736);$y1=520;$y2=1450
  Draw-Frame $g $images.KeyArt ([Drawing.Rectangle]::new($xs[0],$y1,$fw,$fh)) '01 / KEY ART / 2D 7.10H' 'Candidate B structure + Candidate A warm smile' (C '#35E9B7') $fonts.FrameTitle $fonts.FrameSub
  Draw-Frame $g $images.Turnaround ([Drawing.Rectangle]::new($xs[1],$y1,$fw,$fh)) '02 / TURNAROUND / 3-VIEW' 'Front + strict left profile + rear consistency review' (C '#79D7C7') $fonts.FrameTitle $fonts.FrameSub
  Draw-Frame $g $images.Expressions ([Drawing.Rectangle]::new($xs[2],$y1,$fw,$fh)) '03 / EXPRESSIONS / EXACTLY 8' 'Warm, playful, concerned, command, warning, injured-steady' (C '#A78BFA') $fonts.FrameTitle $fonts.FrameSub
  Draw-Frame $g $images.Equipment ([Drawing.Rectangle]::new($xs[0],$y2,$fw,$fh)) '04 / EQUIPMENT STRUCTURE' 'Baton + pack + bioscanner + transparent shield projector VFX' (C '#F7B955') $fonts.FrameTitle $fonts.FrameSub
  Draw-Frame $g $images.Palette ([Drawing.Rectangle]::new($xs[1],$y2,$fw,$fh)) '05 / MATERIAL PALETTE' 'Exact sRGB slots + grayscale readability row' (C '#E67A66') $fonts.FrameTitle $fonts.FrameSub
  Draw-Frame $g $images.Translation ([Drawing.Rectangle]::new($xs[2],$y2,$fw,$fh)) '06 / 2D -> 3D TRANSLATION' 'Expand / delete / combine / physics + next gate' (C '#F09A78') $fonts.FrameTitle $fonts.FrameSub
  $ey=2380;$eh=680;$face=[Drawing.Rectangle]::new(48,$ey,520,$eh);$sil=[Drawing.Rectangle]::new(600,$ey,1500,$eh);$ev=[Drawing.Rectangle]::new(2132,$ey,1916,$eh);foreach($r in @($face,$sil,$ev)){$g.FillRectangle($panel,$r);$g.DrawRectangle($border,$r)}
  Draw-Text $g '128px FACE EVIDENCE' $fonts.EvidenceTitle $white ([Drawing.RectangleF]::new(76,$ey+24,440,34));Draw-Text $g 'Exact source: 128 x 128' $fonts.FrameSub $muted ([Drawing.RectangleF]::new(78,$ey+62,420,28));$old=$g.InterpolationMode;$g.InterpolationMode=[Drawing.Drawing2D.InterpolationMode]::NearestNeighbor;$g.DrawImage($images.Face128,[Drawing.Rectangle]::new(92,$ey+125,432,432));$g.InterpolationMode=$old;Draw-Text $g 'Single-character read only' $fonts.FrameSub $amber ([Drawing.RectangleF]::new(105,$ey+590,430,28)) Center Near
  Draw-Text $g 'HEIGHT-NORMALIZED SILHOUETTE EVIDENCE' $fonts.EvidenceTitle $white ([Drawing.RectangleF]::new(628,$ey+24,1400,34));Draw-Text $g 'Equipment included vs gear minimal' $fonts.FrameSub $muted ([Drawing.RectangleF]::new(630,$ey+62,900,28));Draw-ImageFit $g $images.Silhouette ([Drawing.RectangleF]::new(620,$ey+105,1460,535))
  Draw-Text $g 'EVIDENCE SUMMARY' $fonts.EvidenceTitle $white ([Drawing.RectangleF]::new(2164,$ey+24,800,34));Draw-Badge $g ([Drawing.Rectangle]::new(2164,$ey+86,890,104)) '2D PROPORTION / LOCKED 7.00-7.20H' '7.10H / AUTO PASS' (C '#35E9B7') $fonts.BadgeLabel $fonts.BadgeValue;Draw-Badge $g ([Drawing.Rectangle]::new(3090,$ey+86,926,104)) '3D CONCEPT / LOCKED 5.50-5.60H' '5.55H / CONCEPT PRECHECK' (C '#F7B955') $fonts.BadgeLabel $fonts.BadgeValue;Draw-Badge $g ([Drawing.Rectangle]::new(2164,$ey+220,890,104)) 'FACE / SOURCE SIZE' '128 x 128 / PRESENT' (C '#61E6A5') $fonts.BadgeLabel $fonts.BadgeValue;Draw-Badge $g ([Drawing.Rectangle]::new(3090,$ey+220,926,104)) 'SILHOUETTE / NORMALIZATION' 'SAME CROWN-TO-SOLE' (C '#61E6A5') $fonts.BadgeLabel $fonts.BadgeValue;Draw-Badge $g ([Drawing.Rectangle]::new(2164,$ey+354,890,104)) 'HUMAN APPEAL + FINAL ART' 'PENDING' (C '#F7B955') $fonts.BadgeLabel $fonts.BadgeValue;Draw-Badge $g ([Drawing.Rectangle]::new(3090,$ey+354,926,104)) 'BLENDER / UNITY CHARACTER PROOF' 'NOT TESTED' (C '#FF8EA3') $fonts.BadgeLabel $fonts.BadgeValue;Draw-Text $g 'PRECHECK is evidence readiness only. It is not Gate A/B approval.' $fonts.Summary $amber ([Drawing.RectangleF]::new(2166,$ey+500,1800,34));Draw-Text $g 'Five-character cross-review, rig, joints, camera, sockets and pose proof remain Pending or Not Tested.' $fonts.FrameSub $muted ([Drawing.RectangleF]::new(2167,$ey+548,1800,30))
  $a=@(
   [pscustomobject]@{Id='CHA-A01';Check='Adult-woman read / no childlike regression';State='PRECHECK PASS';Kind='pass'},[pscustomobject]@{Id='CHA-A02';Check='2D target 7.00-7.20H';State='AUTO PASS / 7.10H';Kind='auto'},[pscustomobject]@{Id='CHA-A03';Check='Subculture appeal: face, body, fashion';State='PENDING / HUMAN';Kind='pending'},[pscustomobject]@{Id='CHA-A04';Check='One-line visual hook reads in one image';State='PRECHECK PASS';Kind='pass'},[pscustomobject]@{Id='CHA-A05';Check='Face, hair, body, silhouette, gear anchors';State='PRECHECK PASS';Kind='pass'},[pscustomobject]@{Id='CHA-A06';Check='1 primary + 2 secondary identity features';State='PRECHECK PASS';Kind='pass'},[pscustomobject]@{Id='CHA-A07';Check='Fashion and rescue equipment function link';State='PRECHECK PASS';Kind='pass'},[pscustomobject]@{Id='CHA-A08';Check='Palette distinct across five characters';State='PENDING / 5-ROSTER';Kind='pending'},[pscustomobject]@{Id='CHA-A09';Check='Combat role reads from signature equipment';State='PRECHECK PASS';Kind='pass'},[pscustomobject]@{Id='CHA-A10';Check='Gear-minimal silhouette distinguishes roster';State='PENDING / 5-ROSTER';Kind='pending'},[pscustomobject]@{Id='CHA-A11';Check='128px face distinguishes roster';State='PENDING / 5-ROSTER';Kind='pending'},[pscustomobject]@{Id='CHA-A12';Check='Low-saturation + color-accessibility preview';State='NOT TESTED';Kind='not-tested'},[pscustomobject]@{Id='CHA-A13';Check='No collision with another character motif';State='PENDING / 5-ROSTER';Kind='pending'},[pscustomobject]@{Id='CHA-A14';Check='Off-duty vs mission expression contrast';State='PRECHECK PASS';Kind='pass'},[pscustomobject]@{Id='CHA-A15';Check='External-IP difference/originality analysis';State='PENDING / HUMAN-IP';Kind='pending'},[pscustomobject]@{Id='CHA-A16';Check='2D and 3D scope difference is explicit';State='PRECHECK PASS';Kind='pass'})
  $b=@([pscustomobject]@{Id='CHA-B01';Check='Front / left-profile / rear design consistency';State='CONDITIONAL / BRAID-CAPE';Kind='conditional'},[pscustomobject]@{Id='CHA-B02';Check='Equipment size, grip, fold, emission structure';State='PRECHECK PASS';Kind='pass'},[pscustomobject]@{Id='CHA-B03';Check='Expand / delete / combine rules documented';State='PRECHECK PASS';Kind='pass'},[pscustomobject]@{Id='CHA-B04';Check='5.5-5.6H adult read + Humanoid joints';State='NOT TESTED / BLENDER-UNITY';Kind='not-tested'},[pscustomobject]@{Id='CHA-B05';Check='Major joints clear costume in pose blockout';State='NOT TESTED / BLENDER-UNITY';Kind='not-tested'},[pscustomobject]@{Id='CHA-B06';Check='Face, eyes, hair, outfit, gear material slots';State='PARTIAL / SLOT PROOF';Kind='partial'},[pscustomobject]@{Id='CHA-B07';Check='Emphasis avoids camera, rig, animation blocks';State='NOT TESTED / BLENDER-UNITY';Kind='not-tested'},[pscustomobject]@{Id='CHA-B08';Check='Hair, cape and equipment physics risk budget';State='PRECHECK PASS / NOTE';Kind='pass'},[pscustomobject]@{Id='CHA-B09';Check='Idle, Attack, Skill, Victory motion + sockets';State='PENDING / MOTION-SOCKET';Kind='pending'})
  Draw-Table $g ([Drawing.Rectangle]::new(48,3125,1984,1280)) 'GATE A / CHA-A01-A16 PRECHECK' $a 72 (C '#35E9B7') $fonts.TableTitle $fonts.TableHeader $fonts.TableId $fonts.TableBody $fonts.TableState;Draw-Table $g ([Drawing.Rectangle]::new(2064,3125,1984,790)) 'GATE B / CHA-B01-B09 PRECHECK' $b 74 (C '#F7B955') $fonts.TableTitle $fonts.TableHeader $fonts.TableId $fonts.TableBody $fonts.TableState
  $scope=[Drawing.Rectangle]::new(2064,3940,1984,465);$g.FillRectangle($panel,$scope);$g.DrawRectangle($border,$scope);Draw-Text $g 'PENDING / NOT TESTED BOUNDARY' $fonts.TableTitle $amber ([Drawing.RectangleF]::new(2095,3970,1700,42));Draw-Text $g 'Human Gate A/B approval ........ PENDING' $fonts.Summary $white ([Drawing.RectangleF]::new(2098,4030,1800,34));Draw-Text $g 'Five-character silhouette/face/palette cross-review ........ PENDING' $fonts.Summary $white ([Drawing.RectangleF]::new(2098,4075,1800,34));Draw-Text $g 'Blender proportion, Humanoid rig + joint proof ........ NOT TESTED' $fonts.Summary $white ([Drawing.RectangleF]::new(2098,4120,1800,34));Draw-Text $g 'Unity gameplay camera, animation + socket proof ........ NOT TESTED' $fonts.Summary $white ([Drawing.RectangleF]::new(2098,4165,1800,34));Draw-Text $g 'Final material/shader and physics implementation ........ NOT TESTED' $fonts.Summary $white ([Drawing.RectangleF]::new(2098,4210,1800,34));Draw-Text $g 'Board conclusion: production evidence assembled; final design approval is not granted.' $fonts.Summary $amber ([Drawing.RectangleF]::new(2098,4275,1800,34))
  $g.DrawLine($border,48,4440,4048,4440);Draw-Text $g 'REVIEW ONLY / HUMAN APPROVAL NOT GRANTED' $fonts.Footer $amber ([Drawing.RectangleF]::new(48,4470,1100,34));Draw-Text $g 'Deterministic composite: tools/art/Build-CocoCharacterSheetReview.ps1 | sources remain independently reviewable' $fonts.Footer $muted ([Drawing.RectangleF]::new(1750,4470,2300,34)) Far Near
 }
 finally{$jadePen.Dispose();$border.Dispose();$panel.Dispose();$amber.Dispose();$jade.Dispose();$muted.Dispose();$white.Dispose();$bg.Dispose()}
 $canvas.Save($out,[Drawing.Imaging.ImageFormat]::Png);[pscustomobject]@{Output=$out;Dimensions='4096x4608';Frames=6;EvidencePanels=3;GateARows=$a.Count;GateBRows=$b.Count;Status='REVIEW ONLY';HumanApproval='NOT GRANTED'}
}
finally{$g.Dispose();$canvas.Dispose();foreach($font in $fonts.Values){$font.Dispose()};foreach($image in $images.Values){$image.Dispose()}}
