[CmdletBinding()]
param(
    [string]$ProjectRoot,
    [string]$KeyArtPath='art_refs/characters/iris/concept/Iris_KeyArt_REVIEW_v002.png',
    [string]$TurnaroundPath='art_refs/characters/iris/turnaround/Iris_Turnaround_REVIEW_v002.png',
    [string]$ExpressionPath='art_refs/characters/iris/expressions/Iris_ExpressionSheet_REVIEW_v001.png',
    [string]$Reference3DPath='art_refs/characters/iris/3d_reference/Iris_3DReference_REVIEW_v002.png',
    [switch]$Force
)

Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
Add-Type -AssemblyName System.Drawing
if([string]::IsNullOrWhiteSpace($ProjectRoot)){$ProjectRoot=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'))}else{$ProjectRoot=[IO.Path]::GetFullPath($ProjectRoot)}
function Resolve-In([string]$Path){$p=if([IO.Path]::IsPathRooted($Path)){$Path}else{Join-Path $ProjectRoot $Path};return (Resolve-Path -LiteralPath $p -ErrorAction Stop).Path}
function Resolve-Out([string]$Path){if([IO.Path]::IsPathRooted($Path)){return [IO.Path]::GetFullPath($Path)};return [IO.Path]::GetFullPath((Join-Path $ProjectRoot $Path))}
function C([string]$Hex){return [Drawing.ColorTranslator]::FromHtml($Hex)}
function F([float]$Size,[Drawing.FontStyle]$Style=[Drawing.FontStyle]::Regular){try{return [Drawing.Font]::new('Segoe UI',$Size,$Style,[Drawing.GraphicsUnit]::Pixel)}catch{return [Drawing.Font]::new([Drawing.FontFamily]::GenericSansSerif,$Size,$Style,[Drawing.GraphicsUnit]::Pixel)}}
function Init-G([Drawing.Graphics]$G){$G.SmoothingMode=[Drawing.Drawing2D.SmoothingMode]::AntiAlias;$G.InterpolationMode=[Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic;$G.PixelOffsetMode=[Drawing.Drawing2D.PixelOffsetMode]::HighQuality;$G.CompositingQuality=[Drawing.Drawing2D.CompositingQuality]::HighQuality;$G.TextRenderingHint=[Drawing.Text.TextRenderingHint]::AntiAliasGridFit}
function Save-Png([Drawing.Image]$Image,[string]$Path){$dir=Split-Path -Parent $Path;if(-not[IO.Directory]::Exists($dir)){[IO.Directory]::CreateDirectory($dir)|Out-Null};if([IO.File]::Exists($Path)-and-not$Force){throw "Output exists: $Path. Use -Force."};$Image.Save($Path,[Drawing.Imaging.ImageFormat]::Png)}

if(-not('ReCamp.IrisReview.MaskBuilder' -as [type])){
Add-Type -ReferencedAssemblies 'System.Drawing' -TypeDefinition @'
using System;
using System.Drawing;
using System.Drawing.Imaging;
using System.Runtime.InteropServices;
namespace ReCamp.IrisReview {
 public static class MaskBuilder {
  public static Bitmap Dark(Bitmap source, Rectangle crop){
   using(Bitmap input=source.Clone(crop,PixelFormat.Format24bppRgb)){
    int w=input.Width,h=input.Height,stride;byte[] p=Read(input,out stride);bool[] m=new bool[w*h];
    for(int y=0;y<h;y++){int row=y*stride;for(int x=0;x<w;x++){int i=row+x*3,b=p[i],g=p[i+1],r=p[i+2],max=Math.Max(r,Math.Max(g,b)),min=Math.Min(r,Math.Min(g,b));
     bool laser=r>=72&&r>=g+28&&r>=b+16;bool bright=max>=68;bool skin=r>=74&&r>=g+4&&r>=b-10;bool plum=b>=42&&r>=22&&b>=g+7;bool neutral=max>=38&&(max-min)<=12;m[y*w+x]=(bright||skin||plum||neutral)&&!laser;
    }}RemoveBorder(m,w,h);m=Close(m,w,h,2);RemoveSmall(m,w,h,40);FillHoles(m,w,h);return Render(m,w,h);
   }
  }
  public static Bitmap Light(Bitmap source,Rectangle crop){
   using(Bitmap input=source.Clone(crop,PixelFormat.Format24bppRgb)){
    int w=input.Width,h=input.Height,stride;byte[] p=Read(input,out stride);bool[] m=new bool[w*h];
    for(int y=0;y<h;y++){int row=y*stride,sn=Math.Min(10,Math.Max(1,w/8)),br=0,bg=0,bb=0,count=0;for(int x=0;x<sn;x++){int a=row+x*3,z=row+(w-1-x)*3;bb+=p[a]+p[z];bg+=p[a+1]+p[z+1];br+=p[a+2]+p[z+2];count+=2;}int rr=br/count,gg=bg/count,bbg=bb/count;
     for(int x=0;x<w;x++){int i=row+x*3,b=p[i],g=p[i+1],r=p[i+2],dr=r-rr,dg=g-gg,db=b-bbg;int d=dr*dr+dg*dg+db*db;bool darker=(rr+gg+bbg)-(r+g+b)>=18;m[y*w+x]=d>=320||darker;}
    }m=Close(m,w,h,2);RemoveSmall(m,w,h,20);FillHoles(m,w,h);return Render(m,w,h);
   }
  }
  static byte[] Read(Bitmap b,out int stride){Rectangle r=new Rectangle(0,0,b.Width,b.Height);BitmapData d=b.LockBits(r,ImageLockMode.ReadOnly,PixelFormat.Format24bppRgb);try{stride=Math.Abs(d.Stride);byte[] p=new byte[stride*b.Height];Marshal.Copy(d.Scan0,p,0,p.Length);return p;}finally{b.UnlockBits(d);}}
  static bool[] Close(bool[] m,int w,int h,int r){return Erode(Dilate(m,w,h,r),w,h,r);}
  static bool[] Dilate(bool[] m,int w,int h,int r){bool[] o=new bool[m.Length];for(int y=0;y<h;y++)for(int x=0;x<w;x++){bool v=false;for(int yy=Math.Max(0,y-r);yy<=Math.Min(h-1,y+r)&&!v;yy++)for(int xx=Math.Max(0,x-r);xx<=Math.Min(w-1,x+r);xx++)if(m[yy*w+xx]){v=true;break;}o[y*w+x]=v;}return o;}
  static bool[] Erode(bool[] m,int w,int h,int r){bool[] o=new bool[m.Length];for(int y=0;y<h;y++)for(int x=0;x<w;x++){bool v=true;for(int yy=y-r;yy<=y+r&&v;yy++){if(yy<0||yy>=h){v=false;break;}for(int xx=x-r;xx<=x+r;xx++)if(xx<0||xx>=w||!m[yy*w+xx]){v=false;break;}}o[y*w+x]=v;}return o;}
  static void RemoveSmall(bool[] m,int w,int h,int min){bool[] seen=new bool[m.Length];int[] q=new int[m.Length];int[] dx={-1,0,1,-1,1,-1,0,1},dy={-1,-1,-1,0,0,1,1,1};for(int s=0;s<m.Length;s++){if(!m[s]||seen[s])continue;int a=0,z=0;q[z++]=s;seen[s]=true;while(a<z){int n=q[a++],x=n%w,y=n/w;for(int k=0;k<8;k++){int nx=x+dx[k],ny=y+dy[k];if(nx<0||ny<0||nx>=w||ny>=h)continue;int ni=ny*w+nx;if(m[ni]&&!seen[ni]){seen[ni]=true;q[z++]=ni;}}}if(z<min)for(int i=0;i<z;i++)m[q[i]]=false;}}
  static void RemoveBorder(bool[] m,int w,int h){bool[] seen=new bool[m.Length];int[] q=new int[m.Length];int a=0,z=0;for(int x=0;x<w;x++){int i=x;if(m[i]&&!seen[i]){seen[i]=true;q[z++]=i;}i=(h-1)*w+x;if(m[i]&&!seen[i]){seen[i]=true;q[z++]=i;}}for(int y=0;y<h;y++){int i=y*w;if(m[i]&&!seen[i]){seen[i]=true;q[z++]=i;}i=y*w+w-1;if(m[i]&&!seen[i]){seen[i]=true;q[z++]=i;}}int[] dx={-1,1,0,0},dy={0,0,-1,1};while(a<z){int n=q[a++],x=n%w,y=n/w;for(int k=0;k<4;k++){int nx=x+dx[k],ny=y+dy[k];if(nx<0||ny<0||nx>=w||ny>=h)continue;int ni=ny*w+nx;if(m[ni]&&!seen[ni]){seen[ni]=true;q[z++]=ni;}}}for(int i=0;i<m.Length;i++)if(seen[i])m[i]=false;}
  static void FillHoles(bool[] m,int w,int h){bool[] outside=new bool[m.Length];int[] q=new int[m.Length];int a=0,z=0;for(int x=0;x<w;x++){int i=x;if(!m[i]&&!outside[i]){outside[i]=true;q[z++]=i;}i=(h-1)*w+x;if(!m[i]&&!outside[i]){outside[i]=true;q[z++]=i;}}for(int y=0;y<h;y++){int i=y*w;if(!m[i]&&!outside[i]){outside[i]=true;q[z++]=i;}i=y*w+w-1;if(!m[i]&&!outside[i]){outside[i]=true;q[z++]=i;}}int[] dx={-1,1,0,0},dy={0,0,-1,1};while(a<z){int n=q[a++],x=n%w,y=n/w;for(int k=0;k<4;k++){int nx=x+dx[k],ny=y+dy[k];if(nx<0||ny<0||nx>=w||ny>=h)continue;int ni=ny*w+nx;if(!m[ni]&&!outside[ni]){outside[ni]=true;q[z++]=ni;}}}for(int i=0;i<m.Length;i++)if(!m[i]&&!outside[i])m[i]=true;}
  static Bitmap Render(bool[] m,int w,int h){Bitmap o=new Bitmap(w,h,PixelFormat.Format32bppArgb);Rectangle r=new Rectangle(0,0,w,h);BitmapData d=o.LockBits(r,ImageLockMode.WriteOnly,PixelFormat.Format32bppArgb);try{byte[] p=new byte[Math.Abs(d.Stride)*h];for(int y=0;y<h;y++)for(int x=0;x<w;x++)if(m[y*w+x]){int i=y*d.Stride+x*4;p[i]=38;p[i+1]=30;p[i+2]=24;p[i+3]=255;}Marshal.Copy(p,0,d.Scan0,p.Length);}finally{o.UnlockBits(d);}return o;}
 }
}
'@
}

function New-Face([Drawing.Bitmap]$Source){$crop=[Drawing.Rectangle]::new(28,10,360,360);$o=[Drawing.Bitmap]::new(128,128,[Drawing.Imaging.PixelFormat]::Format24bppRgb);$g=[Drawing.Graphics]::FromImage($o);$a=[Drawing.Imaging.ImageAttributes]::new();try{Init-G $g;$g.CompositingMode=[Drawing.Drawing2D.CompositingMode]::SourceCopy;$a.SetWrapMode([Drawing.Drawing2D.WrapMode]::TileFlipXY);$g.DrawImage($Source,[Drawing.Rectangle]::new(0,0,128,128),$crop.X,$crop.Y,$crop.Width,$crop.Height,[Drawing.GraphicsUnit]::Pixel,$a)}finally{$a.Dispose();$g.Dispose()};return $o}

function New-Palette{
 $items=@(@('HairDeepPlum','#2B243D','Long straight hair base'),@('HairHighlight','#5A4A70','Hair rim / strand groups'),@('CoatColdWhite','#E8EDF2','Long observation coat'),@('CeramicShell','#C9D2DB','Rifle / module casing'),@('InkBodySuit','#171A24','Body suit / gloves'),@('GraphiteMetal','#323842','Lance core / mechanisms'),@('SilverObserver','#AEB8C5','Observation band / trim'),@('CrimsonAccent','#C93149','UI line / lip accent'),@('CrimsonEmission','#FF3B55','Compressed targeting emission'),@('SkinCool','#E3B6AC','Skin base / cool midtone'))
 $o=[Drawing.Bitmap]::new(1600,1160,[Drawing.Imaging.PixelFormat]::Format24bppRgb);$g=[Drawing.Graphics]::FromImage($o);$bg=[Drawing.SolidBrush]::new((C '#F4F7FA'));$card=[Drawing.SolidBrush]::new([Drawing.Color]::White);$tb=[Drawing.SolidBrush]::new((C '#0F172A'));$mb=[Drawing.SolidBrush]::new((C '#475569'));$pen=[Drawing.Pen]::new((C '#CBD5E1'),2);$tf=F 40 ([Drawing.FontStyle]::Bold);$nf=F 22 ([Drawing.FontStyle]::Bold);$hf=F 20 ([Drawing.FontStyle]::Bold);$rf=F 16;$sf=F 14 ([Drawing.FontStyle]::Bold)
 try{Init-G $g;$g.FillRectangle($bg,0,0,$o.Width,$o.Height);$g.DrawString('Iris - Material Palette / REVIEW',$tf,$tb,52,28);$g.DrawString('Exact sRGB material slots | cold-white observation coat + deep-plum precision identity',$hf,$mb,54,84);for($i=0;$i-lt$items.Count;$i++){$col=$i%2;$row=[Math]::Floor($i/2);$x=50+$col*760;$y=135+$row*170;$rect=[Drawing.Rectangle]::new($x,$y,730,145);$sw=[Drawing.Rectangle]::new($x+18,$y+18,150,95);$sb=[Drawing.SolidBrush]::new((C $items[$i][1]));try{$g.FillRectangle($card,$rect);$g.DrawRectangle($pen,$rect);$g.FillRectangle($sb,$sw);$g.DrawRectangle($pen,$sw);$g.DrawString($items[$i][0],$nf,$tb,$x+195,$y+18);$g.DrawString($items[$i][1],$hf,$mb,$x+195,$y+52);$g.DrawString($items[$i][2],$rf,$tb,$x+195,$y+92)}finally{$sb.Dispose()}};$g.DrawString('Grayscale readability',$nf,$tb,54,1000);for($i=0;$i-lt$items.Count;$i++){$col=C $items[$i][1];$v=[int][Math]::Round(.2126*$col.R+.7152*$col.G+.0722*$col.B);$b=[Drawing.SolidBrush]::new([Drawing.Color]::FromArgb($v,$v,$v));try{$x=54+$i*150;$g.FillRectangle($b,$x,1045,132,52);$g.DrawRectangle($pen,$x,1045,132,52);$g.DrawString(($i+1).ToString('00'),$sf,$tb,$x+52,1102)}finally{$b.Dispose()}};$g.DrawString('REVIEW / Human approval Pending / APPROVED: NOT GRANTED',$rf,$mb,1040,1130)}finally{$sf.Dispose();$rf.Dispose();$hf.Dispose();$nf.Dispose();$tf.Dispose();$pen.Dispose();$mb.Dispose();$tb.Dispose();$card.Dispose();$bg.Dispose();$g.Dispose()};return $o
}

function Draw-Figure([Drawing.Graphics]$G,[Drawing.Bitmap]$Image,[Drawing.RectangleF]$Panel,[string]$Label,[int]$Crown,[int]$Chin,[int]$Sole,[double]$Target,[Drawing.Color]$Accent){$ratio=($Sole-$Crown)/[double]($Chin-$Crown);$targetCrown=300.0;$targetSole=1350.0;$scale=($targetSole-$targetCrown)/($Sole-$Crown);$w=$Image.Width*$scale;$h=$Image.Height*$scale;$x=$Panel.X+($Panel.Width-$w)/2;$y=$targetCrown-$Crown*$scale;$fill=[Drawing.SolidBrush]::new((C '#0A1423'));$border=[Drawing.Pen]::new((C '#334155'),2);$guide=[Drawing.Pen]::new($Accent,2);$guide.DashStyle=[Drawing.Drawing2D.DashStyle]::Dash;$white=[Drawing.SolidBrush]::new((C '#F8FAFC'));$accentBrush=[Drawing.SolidBrush]::new($Accent);$lf=F 28 ([Drawing.FontStyle]::Bold);$sf=F 16 ([Drawing.FontStyle]::Bold);try{$G.FillRectangle($fill,$Panel);$G.DrawRectangle($border,$Panel.X,$Panel.Y,$Panel.Width,$Panel.Height);$old=$G.Clip;try{$G.SetClip([Drawing.RectangleF]::new($Panel.X+2,$Panel.Y+70,$Panel.Width-4,$Panel.Height-72));$G.DrawImage($Image,[Drawing.Rectangle]::new([int]$x,[int]$y,[int]$w,[int]$h))}finally{$G.Clip=$old;$old.Dispose()};$G.DrawString($Label,$lf,$white,$Panel.X+24,$Panel.Y+18);$step=($targetSole-$targetCrown)/$ratio;for($i=0;$i-le[Math]::Floor($ratio);$i++){$gy=$targetCrown+$i*$step;$G.DrawLine($guide,$Panel.X+15,$gy,$Panel.Right-15,$gy);$G.DrawString("${i}H",$sf,$accentBrush,$Panel.Right-58,$gy+4)};$G.DrawLine($guide,$Panel.X+15,$targetSole,$Panel.Right-15,$targetSole);$G.DrawString(('{0:F2}H / PASS'-f$ratio),$lf,$accentBrush,$Panel.X+24,$targetSole+18)}finally{$sf.Dispose();$lf.Dispose();$accentBrush.Dispose();$white.Dispose();$guide.Dispose();$border.Dispose();$fill.Dispose()};return $ratio}

function New-Proportion([Drawing.Bitmap]$Key,[Drawing.Bitmap]$Ref){$o=[Drawing.Bitmap]::new(2000,1800,[Drawing.Imaging.PixelFormat]::Format24bppRgb);$g=[Drawing.Graphics]::FromImage($o);$bg=[Drawing.SolidBrush]::new((C '#07111F'));$white=[Drawing.SolidBrush]::new((C '#F8FAFC'));$muted=[Drawing.SolidBrush]::new((C '#94A3B8'));$jade=[Drawing.SolidBrush]::new((C '#61E6A5'));$amber=[Drawing.SolidBrush]::new((C '#F7B955'));$title=F 42 ([Drawing.FontStyle]::Bold);$sub=F 21;$body=F 20;$status=F 28 ([Drawing.FontStyle]::Bold);try{Init-G $g;$g.FillRectangle($bg,0,0,$o.Width,$o.Height);$g.DrawString('Iris - 2D / 3D Proportion Gate Evidence',$title,$white,52,25);$g.DrawString('Deterministic image-space landmarks | selected REVIEW v002 sources',$sub,$muted,54,84);$r2=Draw-Figure $g $Key ([Drawing.RectangleF]::new(40,130,930,1450)) '2D KEY ART / target 7.20-7.40H' 104 270 1316 7.30 (C '#61E6A5');$r3=Draw-Figure $g $Ref ([Drawing.RectangleF]::new(1030,130,930,1450)) '3D CONCEPT / target 5.70-5.80H' 188 410 1464 5.75 (C '#F7B955');$g.DrawString('2D crown/chin/sole: 104 / 270 / 1316',$body,$jade,60,1615);$g.DrawString('3D crown/chin/sole: 188 / 410 / 1464',$body,$amber,1048,1615);$g.DrawString('REVIEW ONLY / HUMAN APPROVAL NOT GRANTED',$status,$white,60,1670);$g.DrawString('Image-space precheck only; anatomy, Blender/Humanoid and Unity runtime proof remain Pending or Not Tested.',$body,$muted,60,1722)}finally{$status.Dispose();$body.Dispose();$sub.Dispose();$title.Dispose();$amber.Dispose();$jade.Dispose();$muted.Dispose();$white.Dispose();$bg.Dispose();$g.Dispose()};return [pscustomobject]@{Image=$o;TwoD=$r2;ThreeD=$r3}}

function New-KeySilhouette{
 $o=[Drawing.Bitmap]::new(864,1280,[Drawing.Imaging.PixelFormat]::Format32bppArgb);$g=[Drawing.Graphics]::FromImage($o);$dark=[Drawing.SolidBrush]::new([Drawing.Color]::FromArgb(255,24,32,43));$clear=[Drawing.SolidBrush]::new([Drawing.Color]::Transparent)
 try{$g.SmoothingMode=[Drawing.Drawing2D.SmoothingMode]::AntiAlias;$g.CompositingMode=[Drawing.Drawing2D.CompositingMode]::SourceCopy;$body=[Drawing.Point[]]@([Drawing.Point]::new(430,34),[Drawing.Point]::new(500,40),[Drawing.Point]::new(550,80),[Drawing.Point]::new(585,160),[Drawing.Point]::new(615,250),[Drawing.Point]::new(620,430),[Drawing.Point]::new(650,580),[Drawing.Point]::new(700,680),[Drawing.Point]::new(755,820),[Drawing.Point]::new(850,1050),[Drawing.Point]::new(842,1110),[Drawing.Point]::new(795,1090),[Drawing.Point]::new(740,990),[Drawing.Point]::new(700,1110),[Drawing.Point]::new(650,1030),[Drawing.Point]::new(620,1080),[Drawing.Point]::new(570,830),[Drawing.Point]::new(535,760),[Drawing.Point]::new(510,930),[Drawing.Point]::new(480,1100),[Drawing.Point]::new(520,1230),[Drawing.Point]::new(470,1246),[Drawing.Point]::new(430,1230),[Drawing.Point]::new(400,1170),[Drawing.Point]::new(370,1246),[Drawing.Point]::new(320,1246),[Drawing.Point]::new(280,1210),[Drawing.Point]::new(300,1080),[Drawing.Point]::new(320,910),[Drawing.Point]::new(300,750),[Drawing.Point]::new(270,690),[Drawing.Point]::new(240,650),[Drawing.Point]::new(200,715),[Drawing.Point]::new(160,700),[Drawing.Point]::new(180,630),[Drawing.Point]::new(230,580),[Drawing.Point]::new(260,520),[Drawing.Point]::new(230,450),[Drawing.Point]::new(240,330),[Drawing.Point]::new(280,230),[Drawing.Point]::new(320,150),[Drawing.Point]::new(340,80),[Drawing.Point]::new(390,45));$g.FillPolygon($dark,$body);$rifle=[Drawing.Point[]]@([Drawing.Point]::new(96,350),[Drawing.Point]::new(150,350),[Drawing.Point]::new(160,600),[Drawing.Point]::new(195,580),[Drawing.Point]::new(210,640),[Drawing.Point]::new(166,690),[Drawing.Point]::new(172,1250),[Drawing.Point]::new(88,1250),[Drawing.Point]::new(84,980),[Drawing.Point]::new(48,980),[Drawing.Point]::new(50,700),[Drawing.Point]::new(82,690));$g.FillPolygon($dark,$rifle);$gap=[Drawing.Point[]]@([Drawing.Point]::new(370,720),[Drawing.Point]::new(430,720),[Drawing.Point]::new(456,1050),[Drawing.Point]::new(430,1190),[Drawing.Point]::new(405,1160),[Drawing.Point]::new(395,930));$g.FillPolygon($clear,$gap)}finally{$clear.Dispose();$dark.Dispose();$g.Dispose()};return $o
}

function New-Silhouette([Drawing.Bitmap]$Key,[Drawing.Bitmap]$Turn){$kc=[Drawing.Rectangle]::new(0,70,864,1280);$tc=[Drawing.Rectangle]::new(100,10,450,820);$km=New-KeySilhouette;$tm=[ReCamp.IrisReview.MaskBuilder]::Light($Turn,$tc);$o=[Drawing.Bitmap]::new(1600,960,[Drawing.Imaging.PixelFormat]::Format24bppRgb);$g=[Drawing.Graphics]::FromImage($o);$bg=[Drawing.SolidBrush]::new((C '#E9EEF4'));$panel=[Drawing.SolidBrush]::new([Drawing.Color]::White);$tb=[Drawing.SolidBrush]::new((C '#0F172A'));$mb=[Drawing.SolidBrush]::new((C '#475569'));$pen=[Drawing.Pen]::new((C '#CBD5E1'),2);$guide=[Drawing.Pen]::new((C '#64748B'),2);$guide.DashStyle=[Drawing.Drawing2D.DashStyle]::Dash;$title=F 38 ([Drawing.FontStyle]::Bold);$sub=F 21;$label=F 24 ([Drawing.FontStyle]::Bold);$body=F 18;try{Init-G $g;$g.FillRectangle($bg,0,0,$o.Width,$o.Height);$g.DrawString('Iris - Height-normalized Silhouette Review',$title,$tb,48,24);$g.DrawString('Observation lance included vs stowed/gear-minimal turnaround front | same crown-to-sole height',$sub,$mb,50,76);$l=[Drawing.Rectangle]::new(40,120,740,790);$r=[Drawing.Rectangle]::new(820,120,740,790);$g.FillRectangle($panel,$l);$g.FillRectangle($panel,$r);$g.DrawRectangle($pen,$l);$g.DrawRectangle($pen,$r);$cy=205.0;$sy=805.0;$ks=600.0/(1316.0-104.0);$ts=600.0/(803.0-29.0);$kw=$km.Width*$ks;$kh=$km.Height*$ks;$kx=410-$kw/2;$ky=$cy-(104-$kc.Y)*$ks;$tw=$tm.Width*$ts;$th=$tm.Height*$ts;$tx=1190-$tw/2;$ty=$cy-(29-$tc.Y)*$ts;$g.DrawImage($km,[Drawing.Rectangle]::new([int]$kx,[int]$ky,[int]$kw,[int]$kh));$g.DrawImage($tm,[Drawing.Rectangle]::new([int]$tx,[int]$ty,[int]$tw,[int]$th));foreach($x in @(58,838)){$g.DrawLine($guide,$x,$cy,$x+704,$cy);$g.DrawLine($guide,$x,$sy,$x+704,$sy)};$g.DrawString('CROWN',$body,$mb,62,$cy-25);$g.DrawString('SOLE',$body,$mb,62,$sy-25);$g.DrawString('CROWN',$body,$mb,842,$cy-25);$g.DrawString('SOLE',$body,$mb,842,$sy-25);$g.DrawString('A | KEY ART / LANCE INCLUDED',$label,$tb,170,842);$g.DrawString('Deterministic outer-contour trace: long coat + lance',$body,$mb,158,882);$g.DrawString('B | TURNAROUND FRONT / GEAR MINIMAL',$label,$tb,900,842);$g.DrawString('Hair + coat vertical identity; modules retained',$body,$mb,920,882);$g.DrawString('REVIEW / Human approval Pending / APPROVED: NOT GRANTED',$body,$mb,1040,929)}finally{$body.Dispose();$label.Dispose();$sub.Dispose();$title.Dispose();$guide.Dispose();$pen.Dispose();$mb.Dispose();$tb.Dispose();$panel.Dispose();$bg.Dispose();$g.Dispose();$km.Dispose();$tm.Dispose()};return $o}

$key=[Drawing.Bitmap]::FromFile((Resolve-In $KeyArtPath));$turn=[Drawing.Bitmap]::FromFile((Resolve-In $TurnaroundPath));$expr=[Drawing.Bitmap]::FromFile((Resolve-In $ExpressionPath));$ref=[Drawing.Bitmap]::FromFile((Resolve-In $Reference3DPath))
try{if($key.Width-ne864-or$key.Height-ne1821){throw 'KeyArt dimensions changed.'};if($turn.Width-ne1536-or$turn.Height-ne1024){throw 'Turnaround dimensions changed.'};if($expr.Width-ne1672-or$expr.Height-ne940){throw 'Expression dimensions changed.'};if($ref.Width-ne887-or$ref.Height-ne1774){throw '3D reference dimensions changed.'};$dir=Resolve-Out 'art_refs/characters/iris/concept';$facePath=Join-Path $dir 'Iris_Face128_REVIEW_v001.png';$palPath=Join-Path $dir 'Iris_MaterialPalette_REVIEW_v001.png';$propPath=Join-Path $dir 'Iris_ProportionGateEvidence_REVIEW_v001.png';$silPath=Join-Path $dir 'Iris_SilhouetteTest_REVIEW_v001.png';$face=New-Face $expr;try{Save-Png $face $facePath}finally{$face.Dispose()};$pal=New-Palette;try{Save-Png $pal $palPath}finally{$pal.Dispose()};$prop=New-Proportion $key $ref;try{Save-Png $prop.Image $propPath}finally{$prop.Image.Dispose()};$sil=New-Silhouette $key $turn;try{Save-Png $sil $silPath}finally{$sil.Dispose()};[pscustomobject]@{Face128=$facePath;Palette=$palPath;Proportion=$propPath;Silhouette=$silPath;TwoDHeads=[Math]::Round($prop.TwoD,2);ThreeDHeads=[Math]::Round($prop.ThreeD,2);Status='REVIEW';HumanApproval='Pending';Approved='NOT GRANTED'}}finally{$ref.Dispose();$expr.Dispose();$turn.Dispose();$key.Dispose()}
